# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - go build . 
    silent: true
  demo:
    cmds:
      - go install .
      - vhs ./demo/realtime.tape
      - vhs ./demo/monitoring.tape
      - vhs ./demo/filtering.tape
