# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - go build . 
    silent: true
  demo:
    cmds:
      - go install .
      - vhs assets/realtime.tape
      - vhs assets/monitoring.tape
      - vhs assets/filtering.tape
