# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - go build . 
    silent: true
  demo:
    cmds:
      - go install .
      - vhs demo.tape
      - xdg-open demo.gif
