# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - go build . 
    silent: true
  demo:
    cmds:
      - go install ..
      - vhs realtime.tape
      - vhs monitoring.tape
      - vhs filtering.tape
